environment: prod
project_name: ORGCHART
report_name: Prod test run 2
jewel_user: himanshu.panchal
jewel_bridge_token: 2c3d6f56-f3af-4fad-8acd-fa0628ff15e31714756016301
email_report: n
email_to: himanshu.panchal@geminisolutions.com
email_cc: ''
tags: '@regression12345'
jewel_screen_shots: y
feature: src/test/resources/features
glue_code: com.qa.orgchart.stepDefinitions
enter_point: https://apis.gemecosystem.com/gemEcosystemDashboard/v1/enter-point
browser_options: '[--incognito]'
console_report: n
event_firing: n
dev:
  browser_name: chrome
  launch_url: https://orgchartdev-np.geminisolutions.com/auth/login
  email: himanshu.panchal@geminisolutions.com
  password: SGltdUF1Z0AxODA4
  browser_timeout: 20
prod:
  browser_name: chrome
  launch_url: https://orgchart.geminisolutions.com/auth/login
  email: himanshu.panchal@geminisolutions.com
  password: SGltdUF1Z0AxODA4
  browser_timeout: 20
